# Сумма одной сделки в USDT
trade_amount_usdt = 6

# Минимальный чистый процентный спред для входа в сделку
spread_threshold_percent = 1

# Комиссия тейкера на бирже в процентах
taker_fee_percent = 0.0

# Процент, который будет добавлен к расчетной стоимости спотового ордера
# для покрытия проскальзывания. 0.5 означает 0.5%.
# Это значение должно быть в кавычках, так как оно обрабатывается как Decimal.
spot_slippage_buffer_percent = "0"

# Уровень логирования: "DEBUG", "INFO", "WARN", "ERROR"
log_level = "INFO"

# Частота обновления UI в миллисекундах (например, раз в секунду)
ui_update_ms = 1000

# Включить реальную торговлю. Установите в `true` с большой осторожностью!
# По умолчанию должно быть `false`.
live_trading_enabled = true

# Максимальное количество одновременно открытых позиций
max_active_positions = 1

# Задержка в миллисекундах между проверками одной и той же пары (троттлинг)
throttle_ms = 50

# URL для подключения к Redis
redis_url = "redis://127.0.0.1/"

# Время в секундах, которое бот должен подождать после открытия позиции
# перед тем, как пытаться ее закрыть. Дает бирже время на клиринг баланса.
position_cooldown_seconds = 5

dust_threshold_usdt = 3