# Сумма одной сделки в USDT
trade_amount_usdt = 8

# Минимальный чистый процентный спред для входа в сделку
spread_threshold_percent = 0.5

# Комиссия тейкера на бирже в процентах
taker_fee_percent = 0.0

# Уровень логирования: "DEBUG", "INFO", "WARN", "ERROR"
log_level = "INFO"

# Частота обновления UI в миллисекундах (например, раз в секунду)
ui_update_ms = 1000

# Включить реальную торговлю. Установите в `true` с большой осторожностью!
# По умолчанию должно быть `false`.
live_trading_enabled = true

# Максимальное количество одновременно открытых позиций
max_active_positions = 1