# Сумма одной сделки в USDT
trade_amount_usdt = 8

# Минимальный чистый процентный спред для входа в сделку
spread_threshold_percent = 0.6

# Комиссия тейкера на бирже в процентах
taker_fee_percent = 0.0

# Процент, который будет добавлен к расчетной стоимости спотового ордера
# для покрытия проскальзывания. 0.5 означает 0.5%.
# Это значение должно быть в кавычках, так как оно обрабатывается как Decimal.
spot_slippage_buffer_percent = "0.5"

# Уровень логирования: "DEBUG", "INFO", "WARN", "ERROR"
log_level = "INFO"

# Частота обновления UI в миллисекундах (например, раз в секунду)
ui_update_ms = 1000

# Включить реальную торговлю. Установите в `true` с большой осторожностью!
# По умолчанию должно быть `false`.
live_trading_enabled = true

# Максимальное количество одновременно открытых позиций
max_active_positions = 2

# Задержка в миллисекундах между проверками одной и той же пары (троттлинг)
throttle_ms = 50

# URL для подключения к Redis
redis_url = "redis://127.0.0.1/"